/*
  在这里添加、删除或修改作品。视频文件放进 videos/ 文件夹后，
  将 src 改为例如 "videos/my-film.mp4"；外部作品可使用 Vimeo、Bilibili 或 YouTube 链接。
*/
const projects = [
  { title: "把风夹在身边", category: "AIGC", year: "2026", duration: "01:12", cover: "covers/wind-film.jpg?v=20260720-wind3", src: "videos/wind-film.mp4", problem: "夹持方式、风力调节与户外使用感，无法靠静态图一次讲清。", deliverable: "AIGC 产品概念短片 / 户外生活方式场景 / 功能动效", description: "以海边、骑行、朋友出游与傍晚使用串联小风扇的夹持与随身体验；用风力数显和气流视觉，把轻巧、强风与户外陪伴感同步讲清。" },
  { title: "多米拉 S1 烤箱", category: "实拍", year: "2026", duration: "01:11", cover: "covers/domira-oven.jpg?v=20260720-domira3", src: "videos/domira-oven.mp4", problem: "烤箱模式与温控参数较多，需要用真实烘焙结果证明它的价值。", deliverable: "产品功能片 / 烘焙测试与食谱场景 / 电商主图素材", description: "从触控操作、双 NTC 温感与正反转大风机切入，再以挞类、蛋糕、水果烘干和多层同烤的实拍结果，呈现一台烤箱覆盖日常烘焙与正餐制作的能力。" },
  { title: "肉松小贝制作", category: "实拍", year: "2026", duration: "02:05", cover: "covers/rousong-xiaobei.jpg?v=20260720-rousong3", src: "videos/rousong-xiaobei.mp4", problem: "食品教程需要清楚呈现关键步骤，才能建立配方和成品的可信度。", deliverable: "配方教程 / 制作过程特写 / 成品组装镜头", description: "完整记录蛋液与打发蛋白、低筋面粉混合、160℃烘烤 20 分钟、放凉切分，再到沙拉酱与肉松包裹成型；把松软、酥香的口感落在可复现的制作过程里。" },
  { title: "悦乐厨烤箱 · 成品展示", category: "实拍结合 AI", year: "2026", duration: "00:57", cover: "covers/yuele-oven.jpg?v=20260720-yuele3", src: "videos/yuele-oven.mp4", problem: "商用烤箱的结构与功能，需要转化为客户能直接判断的出品稳定性。", deliverable: "商用烤箱功能片 / 烘焙测试 / 电商详情素材", description: "通过智能控制、上下独立加热、炉内照明、可视隔热门和双盘大容量等细节，连接面包与点心的烘焙成品，让专业设备能力落到看得见的出品效果。" },
  { title: "老面醒发箱", category: "AIGC", year: "2026", duration: "00:46", cover: "covers/proofing-cabinet.jpg?v=20260720-proofing3", src: "videos/proofing-cabinet.mp4", problem: "醒发成败依赖温度、湿度与时间稳定性，设备价值需要结合实际工序说明。", deliverable: "设备功能短片 / 面点应用场景 / 商厨卖点素材", description: "突出多层大容量内胆、可视玻璃门和多批次醒发空间，结合面团操作与包子成品，说明智能自动醒发以及约 5℃冷藏保存如何帮助减少过度发酵。" },
  { title: "百城切肉机", category: "实拍结合 AI", year: "2026", duration: "00:52", cover: "covers/meat-slicer.jpg?v=20260720-jq1", src: "videos/meat-slicer.mp4", problem: "切片厚度、刀片结构和批量操作能力，是同类设备中最需要被看见的差异。", deliverable: "产品详情片 / 切片厚度演示 / 电商详情素材", description: "围绕 JQ-1 双规格切肉机呈现不锈钢结构、高硬度刀片与可拆洗部件；用 5.5 / 3.5 厚度切片和切肉、绞肉操作过程，把效率与易维护性讲得具体。" },
  { title: "AI 骑行智能眼镜概念片", category: "AIGC", year: "2026", duration: "00:52", cover: "covers/ai-cycling-glasses.jpg?v=20260720-cycling3", src: "videos/ai-cycling-glasses.mp4", problem: "骑行智能设备的使用价值，需要在真实运动节奏里被迅速感知。", deliverable: "AIGC 智能硬件概念片 / 场景叙事 / 交互视觉设计", description: "以落日独骑为主线，将路径指引、道路提示、语音陪伴与分享互动融入骑行过程；通过界面动效让抽象的 AI 功能成为可代入的出行体验。" },
  { title: "Rich Luck 商厨品牌片", category: "AIGC", year: "2026", duration: "00:37", cover: "covers/richluck-brand-film.jpg?v=20260720-richluck3", src: "videos/richluck-brand-film.mp4", problem: "商厨品牌需要在很短时间内同时建立制造规模、技术能力与售后信任。", deliverable: "AIGC 品牌片 / 工厂与展厅展示 / 工程服务场景", description: "从品牌出镜、商厨展厅、智能烤炉，到 CAD 设计、产线巡检和客服响应，搭建“设计—制造—质检—服务”的信任链，强化专业商厨设备品牌形象。" },
  { title: "抓娃娃店活动短片", category: "实拍", year: "2026", duration: "00:26", cover: "covers/claw-machine-store-film.jpg?v=20260720-claw4", src: "videos/claw-machine-store-film.mp4", problem: "门店的人气与互动乐趣，需要被浓缩成让路人立刻想参与的短内容。", deliverable: "门店活动短片 / 探店内容 / 社媒传播素材", description: "由主持人在汇嘉时代购物中心二楼开场，跟随抓取动作、玩偶特写与顾客欢呼，快速建立“人气打卡、现场互动”的抓娃娃店体验。" },
  { title: "母亲节情绪氛围短片", category: "AIGC", year: "2026", duration: "00:44", cover: "covers/home-cooking-story.jpg?v=20260720-add4", src: "videos/home-cooking-story.mp4", problem: "母亲节内容容易停在口号，需要用日常细节让情感自然发生。", deliverable: "AIGC 叙事短片 / 节日传播内容 / 家庭情感场景", description: "从母亲备菜、看手机等待、厨房烹饪与摆盘，到家人围桌共餐，以克制的生活片段完成情绪递进，让节日表达回到一顿饭和一次陪伴。" },
  { title: "AI 校园宣传片", category: "AIGC", year: "2026", duration: "01:33", cover: "covers/spring-campus-film.jpg?v=20260720-add4", src: "videos/spring-campus-film.mp4", problem: "校园宣传不能只展示建筑，需要把生态、学习、科研与项目气质连成统一认知。", deliverable: "AIGC 校园品牌片 / 科研与教学场景 / 招生传播素材", description: "从春日水景、植物与校园航拍，延伸到学生骑行、实验室研究、建筑空间和课堂研讨，最终落到南科大科创 MBA 的创新教育叙事。" },
];
